### ISSUE TITLE
Is the paper available now

### ISSUE THREAD

**Issue by YUE-FAN** [d-li14/HBONet#1]
Thanks for sharing the awesome work! Could you please provide a link to your paper, the link in the README is invalid somehow.

**Comment by d-li14** [comment]
Thanks for your attention. The camera-ready version is ready and should be available in a few days. We will upload it to arxiv upon permission of the corporation. I will notify you then.

**Comment by d-li14** [comment]
original paper available online https://arxiv.org/abs/1908.03888
