### ISSUE TITLE
training epoch 

### ISSUE THREAD

**Issue by stigma0617** [d-li14/HBONet#2]
Hi, 

First of all, congratulation for your acception in ICCV. This work looks nice.

I have two questions,

1) In your paper, these models were trained for 150 epochs while this repo indicates 300epoch.

Which one is correct?

2) This repo notices the dependency of NVIDIA DALI which is not recommended by you. Without the DALI, I can train the model?

**Comment by d-li14** [comment]
Thanks for your reminder and sorry for my previous typo, the training period should be 150 epochs for reproduction which is correct in the training command line.

DALI is optional for you to use which is not necessary, while PyTorch default dataloader will be more stable in my case.

**Comment by stigma0617** [comment]
@d-li14 thanks for your fast reply :)

**Comment by stigma0617** [comment]
@d-li14 

I have another question.

If I use [pytorch default dataloder](https://github.com/d-li14/HBONet/blob/master/utils/dataloaders.py#L223), data augmentations are only randomcrop and flip? 

In your paper, you use scale & aspect ratio augmentations.

The results in your repo are trained by pytorch default dataloader or NVIDIA DALI?

**Comment by d-li14** [comment]
I use the PyTorch dataloader to get all the released results, data augmentations with respect to scale and aspect ratio are included in [RandomResizedCrop](https://pytorch.org/docs/master/torchvision/transforms.html#torchvision.transforms.RandomResizedCrop).

**Comment by stigma0617** [comment]
@d-li14 
Thank you so much!
